### ISSUE TITLE
I believe the `ConfigParser.options` docstring is wrong

### ISSUE THREAD

**Issue by killerswan** [easco/configparser_ex#2]
As I was reading [here](https://hexdocs.pm/configparser_ex/ConfigParser.html#options/2):
https://github.com/easco/configparser_ex/blob/master/lib/configparser.ex#L84

I guess it's compatible with [the Python method](https://docs.python.org/3/library/configparser.html#configparser.ConfigParser.options).  :sweat_smile:

**Comment by easco** [comment]
In what way do you believe the doc string for the function is wrong?  Given the results of parsing and a section identifier the function returns the options that were specified in the configuration within that section.  This is exactly what the doc string says.

**Comment by easco** [comment]
Oh.  I see the problem.
