### ISSUE TITLE
Multi-line strings parsed as one long string

### ISSUE THREAD

**Issue by baldmountain** [easco/configparser_ex#5]
Hi,

I noticed that multi-line strings are parsed into one long line here: https://github.com/easco/configparser_ex/blob/master/lib/ConfigParser/ParseState.ex#L70 It would be nice to have an option to return the parsed string with newlines rather than the lines joined with a space. Maybe a option to parse_string and parse_file like: parse_string("stuff here", continuation: :newline) or parse_string("stuff here", continuation: :space) where the default is the current behavior of space?

**Comment by SLsthompson** [comment]
It appears that the default behavior of ConfigParser in Python is to maintain the newlines.  So this config, taken from the python docs:

```
[My Section]
long: this value continues
   in the next line
```

Will generate the string `'this value continues\nin the next line'` when read from the config.
The fact that the current code joins this into a long string with a space is simply a bug in that light. 

I'm not anxious to add too many configuration options, but it certainly seems that something should be done here.  Let me look into it.

**Comment by easco** [comment]
Since the goal of this library, for better or worse, I've decided to make the default behavior join multi-line values using the newline and allow an option to have multi-line values joined with a space.  This will represent a major, potentially breaking, change so I'll bump the major version number.

**Comment by baldmountain** [comment]
I'd actually prefer the behavior of multi-line values to be joined by a newline. If someone wants the lines joined with a space just do a `String.replace(value, "\n", " ", global: true)` When the lines are joined with a space there is no way to put the newlines back.
